### ISSUE TITLE
能上传但无法下载

### ISSUE THREAD

**Issue by YulinChan** [txthinking/filelink#1]
开发者您好，我使用您的filelink从一台机子上上传了文件，然后从另一台机子（仅含一个ipv6地址）使用filelink下载，但是无法下载，没有报错，但卡住不动，也没有网速，是因为filelink的服务器不支持ipv6的缘故吗？
![image](https://user-images.githubusercontent.com/48314862/84936333-ac7fc500-b10c-11ea-9611-89e5588a08e8.png)

![image](https://user-images.githubusercontent.com/48314862/84936198-7cd0bd00-b10c-11ea-8961-928b6c6ef12d.png)

**Comment by txthinking** [comment]
. 点后面多了一个空格?

**Comment by YulinChan** [comment]
确实，但是是它自动生成的，我没改过。
我又试了一下，这次生成的链接没有空格，但还是纹丝不动
![image](https://user-images.githubusercontent.com/48314862/84983422-52fab300-b16b-11ea-8265-387c9e8f39ae.png)

**Comment by YulinChan** [comment]
本机上传，本机能下，我还想在另一国内的机子试试的，但是nami安装filelink一直卡住不动

**Comment by txthinking** [comment]
估计是不支持IPv6 Only的网络

**Comment by YulinChan** [comment]
ipv6 only的机子上上传下载都不行，应该是filelink服务器只有ipv4地址吧，我在我电脑上ping filelink.io出现的是ipv4的地址，我的电脑是ipv6优先，一般情况有ipv6地址就会连接ipv6地址。

**Comment by txthinking** [comment]
v20220601 鉴于流量成本，服务端 `server.js` 和 客户端 `client.js` 均已开源，可以自己部署自己的 server
